### ISSUE TITLE
browserify.ignore 

### ISSUE THREAD

**Issue by timshannon** [gobblejs/gobble-browserify#4]
Is there anyway to pass values into the ignore call?  It's not a browserify option, but called directly on the browserify object: https://www.npmjs.com/package/browserify#b-ignore-file

Or should I just call my own browserify function, and use it there?

**Comment by Rich-Harris** [comment]
It *should* be possible - I haven't ever really ventured beyond the basics of browserify, but if I understand correctly [this](https://github.com/gobblejs/gobble-browserify/blob/ignore/index.js#L18-L20) should work (haven't tried it, just did it through the GH web interface, so YMMV).

If it does work, I'll merge it in later (don't have time right now sadly).

I guess it should probably support transforms in a similar fashion...

**Comment by timshannon** [comment]
Yeah, that's what I just put in my custom browserify function, and it works fine.

One small change before you commit yours though; you should call `b.ignore( options.ignore );` not `browserify.ignore( options.ignore );`

Other than that, it'll work perfect for me.

Thanks

**Comment by Rich-Harris** [comment]
@timshannon I've just released 0.4.0, which adds support for `ignore` and `exclude` along with `expose` (I was searching for *ages* to try and figure out how to insist that browserify use `./this/particular/foo.js` for `require('foo')` - `expose` is a shorthand for doing that).

It also adds a generic `configure` hook for ad hoc configuration. Details on the [README](https://github.com/gobblejs/gobble-browserify)
